// <auto-generated />
using System;
using Finder.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Finder.Db.Migrations
{
    [DbContext(typeof(FinderDbContext))]
    partial class BotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Finder.Bot.Db.Models.CountdownModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("PingRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("PingUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("UnixTime")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Countdowns");
                });

            modelBuilder.Entity("Finder.Bot.Db.Models.EconomyModel", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Bank")
                        .HasColumnType("integer");

                    b.Property<int>("Money")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("Economy");
                });

            modelBuilder.Entity("Finder.Bot.Db.Models.InventoryModel", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "UserId", "ItemId");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("Finder.Bot.Db.Models.LevellingModel", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Exp")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("Leveling");
                });

            modelBuilder.Entity("Finder.Bot.Db.Models.PollVoter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PollMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("PollMessageId");

                    b.ToTable("PollVoters");
                });

            modelBuilder.Entity("Finder.Bot.Db.Models.PollsModel", b =>
                {
                    b.Property<decimal>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("MessageId");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("Finder.Bot.Db.Models.SettingsModel", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Setting")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Finder.Bot.Db.Models.TicketClaimer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("TicketChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("TicketChannelId");

                    b.ToTable("TicketClaimers");
                });

            modelBuilder.Entity("Finder.Bot.Db.Models.TicketUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("TicketChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("TicketChannelId");

                    b.ToTable("TicketUsers");
                });

            modelBuilder.Entity("Finder.Bot.Db.Models.TicketsModel", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("IntroMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ChannelId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Finder.Bot.Db.Models.UserLogsModel", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Bans")
                        .HasColumnType("integer");

                    b.Property<int>("Kicks")
                        .HasColumnType("integer");

                    b.Property<int>("Mutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TempBan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TempMute")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Warns")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("Finder.Db.Models.AddonsModel", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Addon")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId", "Addon");

                    b.ToTable("Addons");
                });

            modelBuilder.Entity("Finder.Db.Models.Web.UserSettingsModel", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Setting")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "Setting");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Finder.Bot.Db.Models.PollVoter", b =>
                {
                    b.HasOne("Finder.Bot.Db.Models.PollsModel", "Poll")
                        .WithMany("Voters")
                        .HasForeignKey("PollMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("Finder.Bot.Db.Models.TicketClaimer", b =>
                {
                    b.HasOne("Finder.Bot.Db.Models.TicketsModel", "Ticket")
                        .WithMany("Claimers")
                        .HasForeignKey("TicketChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Finder.Bot.Db.Models.TicketUser", b =>
                {
                    b.HasOne("Finder.Bot.Db.Models.TicketsModel", "Ticket")
                        .WithMany("Users")
                        .HasForeignKey("TicketChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Finder.Bot.Db.Models.PollsModel", b =>
                {
                    b.Navigation("Voters");
                });

            modelBuilder.Entity("Finder.Bot.Db.Models.TicketsModel", b =>
                {
                    b.Navigation("Claimers");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
